using System.Text.Json;
using System.Text.Json.Serialization;
using Corti.Core;

namespace Corti;

[Serializable]
public record GuidedTemplate : IJsonOnDeserialized
{
    [JsonExtensionData]
    private readonly IDictionary<string, JsonElement> _extensionData =
        new Dictionary<string, JsonElement>();

    /// <summary>
    /// The UUID of the template.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; set; }

    /// <summary>
    /// Reference to the template to inherit template instructions and sections from. Inherits from published version by default.
    /// </summary>
    [JsonPropertyName("inheritedFromId")]
    public string? InheritedFromId { get; set; }

    /// <summary>
    /// True if the template was auto-generated based on the section-composed POST /documents request.
    /// </summary>
    [JsonPropertyName("autoGenerated")]
    public bool? AutoGenerated { get; set; }

    /// <summary>
    /// Whether this template was created by the user or is a Corti standard resource.
    /// </summary>
    [JsonPropertyName("source")]
    public GuidedTemplateSource? Source { get; set; }

    /// <summary>
    /// The name of this template. Not passed to the LLM.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; set; }

    /// <summary>
    /// A description for this template. Not passed to the LLM.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }

    /// <summary>
    /// BCP 47 language subtags this template has been tweaked for (e.g. `["fr", "de"]`). Empty means no language-specific tweaks.
    /// </summary>
    [JsonPropertyName("languages")]
    public IEnumerable<string> Languages { get; set; } = new List<string>();

    /// <summary>
    /// ISO 3166-1 alpha-3 country codes this template has been tweaked for (e.g. `["BEL"]`). Empty means no region-specific tweaks.
    /// </summary>
    [JsonPropertyName("regions")]
    public IEnumerable<string> Regions { get; set; } = new List<string>();

    /// <summary>
    /// Clinical specialties this template has been tweaked for. Empty means no specialty-specific tweaks.
    /// </summary>
    [JsonPropertyName("specialties")]
    public IEnumerable<string> Specialties { get; set; } = new List<string>();

    /// <summary>
    /// The available labels to use as query param filter in the LIST /templates endpoint.
    /// </summary>
    [JsonPropertyName("labels")]
    public IEnumerable<Label> Labels { get; set; } = new List<Label>();

    /// <summary>
    /// Access policies for this template.
    /// </summary>
    [JsonPropertyName("policies")]
    public IEnumerable<GuidedTemplatePolicy>? Policies { get; set; }

    [JsonPropertyName("publishedVersion")]
    public GuidedTemplateVersion? PublishedVersion { get; set; }

    /// <summary>
    /// The original timestamp when the template was created.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public required DateTime CreatedAt { get; set; }

    /// <summary>
    /// The original timestamp when the template was last updated.
    /// </summary>
    [JsonPropertyName("updatedAt")]
    public required DateTime UpdatedAt { get; set; }

    /// <summary>
    /// Present when the template has been deleted. GET by ID still returns the full resource with this field populated.
    /// </summary>
    [JsonPropertyName("deletedAt")]
    public DateTime? DeletedAt { get; set; }

    [JsonIgnore]
    public ReadOnlyAdditionalProperties AdditionalProperties { get; private set; } = new();

    void IJsonOnDeserialized.OnDeserialized() =>
        AdditionalProperties.CopyFromExtensionData(_extensionData);

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
