using System.Text.Json;
using System.Text.Json.Serialization;
using Corti.Core;

namespace Corti;

[Serializable]
public record GuidedSection : IJsonOnDeserialized
{
    [JsonExtensionData]
    private readonly IDictionary<string, JsonElement> _extensionData =
        new Dictionary<string, JsonElement>();

    /// <summary>
    /// The UUID of the section.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; set; }

    /// <summary>
    /// Reference to the section to inherit generation configuration from. Inherits from published version by default.
    /// </summary>
    [JsonPropertyName("inheritedFromId")]
    public string? InheritedFromId { get; set; }

    /// <summary>
    /// True if the section was auto-generated as part of an inline section-composed POST /documents request.
    /// </summary>
    [JsonPropertyName("autoGenerated")]
    public bool? AutoGenerated { get; set; }

    /// <summary>
    /// Whether this section was created by the user or from the Corti standard resources.
    /// </summary>
    [JsonPropertyName("source")]
    public GuidedSectionSource? Source { get; set; }

    /// <summary>
    /// The name of the section.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; set; }

    /// <summary>
    /// BCP 47 languages this section has been tweaked for. Empty means no language-specific tweaks.
    /// </summary>
    [JsonPropertyName("languages")]
    public IEnumerable<string> Languages { get; set; } = new List<string>();

    /// <summary>
    /// ISO 3166-1 alpha-3 country codes this section has been tweaked for. Empty means no region-specific tweaks.
    /// </summary>
    [JsonPropertyName("regions")]
    public IEnumerable<string> Regions { get; set; } = new List<string>();

    /// <summary>
    /// Clinical specialties this section has been tweaked for. Empty means no specialty-specific tweaks.
    /// </summary>
    [JsonPropertyName("specialties")]
    public IEnumerable<string> Specialties { get; set; } = new List<string>();

    /// <summary>
    /// The description for the section.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }

    /// <summary>
    /// The labels available to use as query param filter in the LIST /sections endpoint.
    /// </summary>
    [JsonPropertyName("labels")]
    public IEnumerable<GuidedLabel> Labels { get; set; } = new List<GuidedLabel>();

    /// <summary>
    /// The currently published version with section inheritance fully resolved. Present when a version has been published.
    /// </summary>
    [JsonPropertyName("publishedVersion")]
    public GuidedSectionVersion? PublishedVersion { get; set; }

    /// <summary>
    /// The original timestamp when the section was created.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public required DateTime CreatedAt { get; set; }

    /// <summary>
    /// The original timestamp when the section was last updated.
    /// </summary>
    [JsonPropertyName("updatedAt")]
    public required DateTime UpdatedAt { get; set; }

    /// <summary>
    /// Present when the section has been deleted. GET by ID still returns the full resource with this field populated.
    /// </summary>
    [JsonPropertyName("deletedAt")]
    public DateTime? DeletedAt { get; set; }

    /// <summary>
    /// Access policies for this section.
    /// </summary>
    [JsonPropertyName("policies")]
    public IEnumerable<GuidedSectionPolicy>? Policies { get; set; }

    [JsonIgnore]
    public ReadOnlyAdditionalProperties AdditionalProperties { get; private set; } = new();

    void IJsonOnDeserialized.OnDeserialized() =>
        AdditionalProperties.CopyFromExtensionData(_extensionData);

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
