name: ci

on: [push]

env:
  DOTNET_NOLOGO: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Install tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore src/Corti/Corti.csproj

      - name: Build
        run: dotnet build src/Corti/Corti.csproj --no-restore -c Release

      - name: Restore test dependencies
        run: dotnet restore src/Corti.Test/Corti.Test.csproj

      - name: Build tests
        run: dotnet build src/Corti.Test/Corti.Test.csproj --no-restore -c Release

      - name: Test
        run: dotnet test src/Corti.Test/Corti.Test.csproj --no-restore --no-build -c Release

